services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - UID_HOST=${UID_HOST:-1000}
        - GID_HOST=${GID_HOST:-1000}
    container_name: faberlicai-php
    restart: unless-stopped
    working_dir: /var/www/html
    command: >
      sh -c "
      php artisan queue:work --sleep=3 --tries=3 --timeout=60 &
      php-fpm"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - faberlicai-network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: faberlicai-nginx
    restart: unless-stopped
    ports:
      - "${IP_HOST}:${NGINX_PORT}:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - PHP_FPM_HOST=${PHP_FPM_HOST}
      - PHP_FPM_PORT=${PHP_FPM_PORT}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - faberlicai-network

  mysql:
    image: mysql:8.0
    container_name: faberlicai-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${IP_HOST}:${DB_PORT}:3306"
    networks:
      - faberlicai-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}" ]
      interval: 5s
      timeout: 10s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: faberlicai-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - faberlicai-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 3
    command: redis-server --appendonly yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: faberlicai-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${IP_HOST}:8081:80"
    depends_on:
      - mysql
    networks:
      - faberlicai-network
volumes:
  mysql_data:
  redis_data:

networks:
  faberlicai-network:
    external: true