services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        - UID_HOST=${UID_HOST:-1000}
        - GID_HOST=${GID_HOST:-1000}
    container_name: faberlicai-php
    restart: unless-stopped
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network

  nginx:
    image: nginx:${NGINX_VERSION:-alpine}
    container_name: faberlicai-nginx
    restart: unless-stopped
    ports:
      - "${IP_HOST}:${NGINX_PORT}:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - PHP_FPM_HOST=${PHP_FPM_HOST}
      - PHP_FPM_PORT=${PHP_FPM_PORT}
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf.template
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: faberlicai-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${IP_HOST}:${DB_PORT}:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}" ]
      interval: 5s
      timeout: 10s
      retries: 20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: faberlicai-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${IP_HOST}:8081:80"
    depends_on:
      - mysql
    networks:
      - app-network

  samba-ad:
    image: nowsci/samba-domain
    container_name: faberlicai-samba-ad
    hostname: dc1.faberlicai.local
    ports:
      - "5389:53"           # DNS - нестандартный внешний порт
      - "5389:53/udp"
      - "88:88"
      - "389:389"           # LDAP оставляем стандартным
      - "4455:445"           # SMB оставляем стандартным
      - "139:139"
      - "464:464"
      - "3268:3268"
    environment:
      - DOMAIN=faberlicai.local
      - DOMAINPASS=SecurePass123
      - HOSTIP=127.0.0.1
      - DNSFORWARDER=8.8.8.8
      - INSECURE_DOMAIN=true
    volumes:
      - samba_data:/var/lib/samba
      - samba_config:/etc/samba
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql_data:
  samba_data:
  samba_config:

networks:
  app-network:
    driver: bridge