[PHP]
#extension=ldap.so
#extension=zip.so
#extension=gd.so
#extension=mbstring.so
#extension=pdo_mysql.so
#extension=exif.so
#extension=pcntl.so
#extension=bcmath.so

display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On

memory_limit = 512M
max_execution_time = 300
upload_max_filesize = 100M
post_max_size = 100M

date.timezone = Europe/Moscow
short_open_tag = Off